set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p')

set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p')

if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif
syntax	on

" change cursor between normal & insert mode
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

set     nocompatible
" make backspace work
set     backspace=indent,eol,start
" clipboard
set     clipboard=unnamed,unnamedplus
" file format
set     encoding=utf-8
set     fileformat=unix
" tab
set     tabstop=4 
set     softtabstop=4
set     shiftwidth=4 
set     expandtab 
set     autoindent
" highlight search
set 	hlsearch
set     incsearch
" mouse
set     mouse=a
" number
set		number relativenumber
