#
# ~/.config/bash/bash_profile
#

# source $XDG_CONFIG_HOME/bash/bashrc | default: [[ -f ~/.bashrc ]] && . ~/.bashrc
# [[ -f ~/.config/bash/bashrc ]] && . ~/.config/bash/bashrc
[[ -f $XDG_CONFIG_HOME/bash/bashrc ]] && . $XDG_CONFIG_HOME/bash/bashrc

# ==== xdg base user & system dirs ====
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_RUNTIME_DIR="/run/user/$UID"

export XDG_DATA_DIRS="/usr/local/share:/usr/share"
export XDG_CONFIG_DIRS="/etc/xdg"

# ==== bash ====
# export HISTFILE="$XDG_CONFIG_HOME"/bash/.bash_history
# export HISTFILE="$HOME/.config/bash/.bash_history"
export HISTFILE="$XDG_STATE_HOME"/bash/history
export LESSHISTFILE=-
export BASH_COMPLETION_USER_FILE="$XDG_CONFIG_HOME"/bash-completion/bash_completion

# ==== xorg ====
# xrdb -load ~/.config/X11/xresources
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc
export XSERVERRC="$XDG_CONFIG_HOME"/X11/xserverrc
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority

# ==== Apps ====
# conky if i use it
# conky --config="$XDG_CONFIG_HOME"/conky/conkyrc
# ffmpeg
export FFMPEG_DATADIR="$XDG_CONFIG_HOME"/ffmpeg
# gdb
# gdb -nh -x "$XDG_CONFIG_HOME"/gdb/init
export GDBHISTFILE="$XDG_DATA_HOME"/gdb/history
# gnupg
# gpg2 --homedir "$XDG_DATA_HOME"/gnupg
# Note that this currently does not work out-of-the-box using systemd user units and socket-based activation,
# since the socket directory changes based on the hash of $GNUPGHOME.
# You can get the new socket directory using "gpgconf --dry-run --create-socketdir" and
# have to modify the systemd user units to listen on the correct sockets accordingly.
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
# gtk
export GTK_RC_FILES="$XDG_CONFIG_HOME"/gtk-1.0/gtkrc
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
# nvidia
# nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings
export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
# (neo)vim
# export GVIMINIT='let $MYGVIMRC = !has("nvim") ? "$XDG_CONFIG_HOME/vim/gvimrc" : "$XDG_CONFIG_HOME/nvim/init.gvim" | so $MYGVIMRC'
# export VIMINIT='let $MYVIMRC = !has("nvim") ? "$XDG_CONFIG_HOME/vim/vimrc" : "$XDG_CONFIG_HOME/nvim/init.vim" | so $MYVIMRC'
# qt5
export QT_QPA_PLATFORMTHEME="qt5ct"
# vim
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
# wget
# echo hsts-file \= "$XDG_CACHE_HOME"/wget-hsts >> "$XDG_CONFIG_HOME/wgetrc"
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
# zoom, if i used it
export SSB_HOME="$XDG_DATA_HOME"/zoom

# ==== programming ====
# android
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME"/android
export ANDROID_AVD_HOME="$XDG_DATA_HOME"/android
export ANDROID_EMULATOR_HOME="$XDG_DATA_HOME"/android
export ADB_VENDOR_KEY="$XDG_CONFIG_HOME"/android
# go
export GOPATH="$XDG_DATA_HOME"/go
# haskell
export STACK_ROOT="$XDG_DATA_HOME"/stack
export CABAL_CONFIG="$XDG_CONFIG_HOME"/cabal/config
export CABAL_DIR="$XDG_DATA_HOME"/cabal
# java
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
# node.js
export NODE_REPL_HISTORY="$XDG_DATA_HOME"/node_repl_history
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
# python
export AZURE_CONFIG_DIR=$XDG_DATA_HOME/azure
export GRIPHOME="$XDG_CONFIG_HOME/grip"
export PYTHON_EGG_CACHE="$XDG_CACHE_HOME"/python-eggs
export PYLINTHOME="$XDG_CACHE_HOME"/pylint
# ruby
export BUNDLE_USER_CONFIG="$XDG_CONFIG_HOME"/bundle
export BUNDLE_USER_CACHE="$XDG_CACHE_HOME"/bundle
export BUNDLE_USER_PLUGIN="$XDG_DATA_HOME"/bundle
# rust
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup

# gradle
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
# mySql
# ~/.my.cnf only supported for mysql-server, not mysql-client [155]
# ~/.mylogin.cnf unsupported
export MYSQL_HISTFILE="$XDG_DATA_HOME"/mysql_history
# SQLite
# sqlite3 -init "$XDG_CONFIG_HOME"/sqlite3/sqliterc
export SQLITE_HISTORY=$XDG_DATA_HOME/sqlite_history
